Reutilizacao
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #106
Opened 2022-04-15 13:52 UTC by IanFPFerreira

## Issue 
Resolve #101

## Descrição
Documento de reutilização de software

## Checklist:

- [ ] O código segue os padrões do projeto
- [ ] Não tem erros ortográficos
- [ ] Não falta nenhuma técnica de reutilização relevante

2022-04-15 15:46 UTC, joaovaladao approved these changes
Boa família S2

2022-04-15 18:53 UTC, hryds approved these changes

2022-04-16 19:57 UTC, italovinicius18 requested changes

2022-04-16 19:57 UTC, italovinicius18 commented on docs/ArquiteturaEReutilizacao/Reutilizacao/Reutilizacao.md
> +
Adicionar o ambiente Node que facilitou na implementação e as bibliotecas Axios e qs que serviram respectivamente para a conexão com a API e já o qs serviu para traduzir os objetos js para querystring, facilitando nas requisições

2022-04-16 19:57 UTC, italovinicius18 commented on docs/ArquiteturaEReutilizacao/Reutilizacao/Reutilizacao.md
> +
Adicionar biblioteca cors e mssql que serviram respectivamente para configurar opções de segurança das conexões dos clientes e conexão do backend com o sql server por meio da chaves de autenticação

2022-04-18 11:05 UTC, italovinicius18 approved these changes

2022-04-18 11:06 UTC, merged