DAS
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #110
Opened 2022-04-15 14:22 UTC by hryds

## Issue 
Resolve #100

## Descrição

Documento de arquitetura

## Checklist:

- [ ] O código segue os padrões do projeto
- [ ] Não há erros ortográficos

2022-04-15 15:58 UTC, gabrielavelino commented on docs/ArquiteturaEReutilizacao/DAS/DAS.md
> +<figcaption>Figura 7 - Cadastro de Usuário</figcaption>
A imagem não esta aparecendo.

2022-04-15 15:58 UTC, gabrielavelino commented on docs/ArquiteturaEReutilizacao/DAS/DAS.md
> +<figcaption>Figura 8 - Candidatar em uma vaga de estágio</figcaption>
Essa imagem também não esta aparecendo.

2022-04-15 16:11 UTC, gabrielavelino approved these changes

2022-04-15 16:11 UTC, gabrielavelino commented on docs/ArquiteturaEReutilizacao/DAS/DAS.md
> +<figcaption>Figura 7 - Cadastro de Usuário</figcaption>
Imagem aparentemente quebrada, mas no mkdocs tudo aparenta estar correto.

2022-04-15 16:11 UTC, gabrielavelino commented on docs/ArquiteturaEReutilizacao/DAS/DAS.md
> +<figcaption>Figura 8 - Candidatar em uma vaga de estágio</figcaption>
Imagem aparentemente quebrada, mas no mkdocs tudo aparenta estar correto.

2022-04-15 17:16 UTC, AlvaroLeles approved these changes

2022-04-15 18:58 UTC, IanFPFerreira approved these changes

2022-04-16 13:46 UTC, italofernandes13 requested changes

2022-04-16 13:46 UTC, italofernandes13 commented on docs/ArquiteturaEReutilizacao/DAS/DAS.md
> +| Pós-condições   | O usuário tera seus dados atualizados                                                                                 |
O documento está ótimo. O único erro que encontrei foi o "tera", o correto seria "terá".

2022-04-16 18:35 UTC, Nathanserra approved these changes

2022-04-16 19:01 UTC, joaovaladao approved these changes

2022-04-16 19:47 UTC, italovinicius18 approved these changes

2022-04-17 23:40 UTC, merged