Personas update
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #27
Opened 2022-01-26 20:29 UTC by italofernandes13

## Issue 
 #21

## Descrição
Desenvolvemos as personas e anti-persona representando os perfis de usuários para a aplicação do nosso projeto.

## Checklist:

- [ ] Reunir com os membros;
- [ ] Desenvolver a persona primária;
- [ ] Desenvolver a persona secundária;
- [ ] Desenvolver a persona terciária;
- [ ] Desenvolver a anti-persona;

## Como validar?
- [ ] Verificar possíveis erros ortográficos;

2022-01-26 20:36 UTC, gabrielavelino commented
Revisar erro ortográfico na persona terciária na parte de tarefas.

2022-01-26 23:24 UTC, italovinicius18 commented
Resolve #21

2022-01-27 14:34 UTC, italovinicius18 requested changes

2022-01-27 14:34 UTC, italovinicius18 commented on docs/Base/IE/Personas.md
> +Um dos passos mais importantes do projeto é conhecer o perfil do usuário, pois assim teremos ideia do público alvo e de como o sistema vai se comportar perante a esse público, descrevendo cada cada s
Descrevendo cada cada ?

2022-01-27 14:34 UTC, italovinicius18 commented on docs/Base/IE/Personas.md
> +<p style="text-indent: 20px; text-align: justify">
Podem remover a tag p, coloquem só o texto pois já é interpretado como parágrafo

2022-01-27 14:34 UTC, italovinicius18 commented on docs/Base/IE/Personas.md
> +Uma das melhores formas de auxiliar o designer do sistema na análise dos perfis dos usuários é por meio da criação de personas, que são personagens criados de maneira fictícia que servem para represe
Deve ser "reapresentada"

2022-01-27 14:34 UTC, italovinicius18 commented on docs/Base/IE/Personas.md
> +|   Habilidades   | joga basquete muito bem, é muito inteligente e tira notas altas, é o mais rápido da turma e sabe um pouco de inglês |
Iniciar com maiúscula

2022-01-27 14:39 UTC, italovinicius18 requested changes

2022-01-27 14:39 UTC, italovinicius18 commented on docs/Base/IE/Personas.md
> +Versão | Data | Modificação | Autor(es)
Adicionar barra vertical no fim da linha

Por ex: 

Versão | Data | Modificação | Autor(es) |

2022-01-27 17:12 UTC, gabrielavelino approved these changes
Erros apontados foram consertados.

2022-01-27 22:43 UTC, merged

2022-01-27 22:44 UTC, italovinicius18 reviewed
Tudo certo, já fiz o merge