Introspeccao
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #46
Opened 2022-02-02 12:05 UTC by IanFPFerreira

## Issue 
Resolve #28

## Descrição
Criação do documento de Introspecção

## Como validar?
- [ ] O código segue os padrões do projeto
- [ ] A aplicação da técnica está correta

2022-02-02 17:44 UTC, joaovaladao requested changes
No parágrafo de Metodologia apresenta um erro de concordância ("os usuários alvos DO aplicação");

2022-02-03 13:50 UTC, hryds requested changes

2022-02-03 13:50 UTC, hryds commented on docs/Base/PNOAE/Requisitos/Elicitacao/Introspeccao.md
> +Com o uso da Introspecção, vimos que seria possível, por meio das [personas](../../../IE/Personas.md), comprovar e explorar diferentes realidades e casos de uso, pois desta maneira conseguiríamos ima
trocar "atenderia" por "atenderiam"

2022-02-03 15:29 UTC, hryds approved these changes

2022-02-03 16:42 UTC, joaovaladao approved these changes

2022-02-03 17:18 UTC, merged