Diagrama de pacotes
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #74
Opened 2022-02-16 22:49 UTC by GRVial

## Issue 
Resolve #61 

## Descrição
Feito documento e diagrama.

## Checklist:

- [ ] O documento estar correto
- [ ] O documento estar de acordo com o esperado para o projeto

2022-02-17 15:20 UTC, IanFPFerreira requested changes

2022-02-17 15:20 UTC, IanFPFerreira commented on docs/Modelagem/ME/DiagramaDePacotes.md
> +O desenvolvimento do diagrama leva em consideração as técnologias e estruturas que serão adotadas no projeto. Sendo assim, o diagrama de pacotes representa os módulos que serão desenvolvidos na API d
Tirar o acento da palavra 'tecnologias'

2022-02-17 15:25 UTC, IanFPFerreira requested changes

2022-02-17 15:25 UTC, IanFPFerreira commented on docs/Modelagem/ME/DiagramaDePacotes.md
> +
Adicionar legenda para a figura

2022-02-17 18:37 UTC, guilhermemoraisr requested changes
As minhas observações são as mesmas do Ian. No geral, o documento está ótimo, basta corrigir esse erro de escrita e adicionar a legenda da imagem, utilizando a tag figcaption.

2022-02-17 18:37 UTC, guilhermemoraisr commented on docs/Modelagem/ME/DiagramaDePacotes.md
> +
Adicionar legenda para a figura

2022-02-17 18:37 UTC, guilhermemoraisr commented on docs/Modelagem/ME/DiagramaDePacotes.md
> +O desenvolvimento do diagrama leva em consideração as técnologias e estruturas que serão adotadas no projeto. Sendo assim, o diagrama de pacotes representa os módulos que serão desenvolvidos na API d
Concordo.

2022-02-17 22:32 UTC, IanFPFerreira approved these changes
Está tudo certo!

2022-02-18 02:04 UTC, guilhermemoraisr approved these changes
Tudo certo!

2022-02-18 02:05 UTC, merged