Reuniao atas modelagem
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #79
Opened 2022-02-17 02:26 UTC by italofernandes13

## Issue 
Resolve #60

## Descrição
Criação do documento e das Atas de Reuniões

## Checklist:

- [ ] verificar erros ortográficos
- [ ] verificar se corresponde a reunião do grupo

2022-02-17 18:20 UTC, guilhermemoraisr requested changes
Corrigir o erro ortográfico

2022-02-17 18:20 UTC, guilhermemoraisr commented on docs/Modelagem/Reunioes/Atas/Ata1.md
> +Esta ata apresenta as informações do que foi feito e abordado entre a equipe referente a segunda entrega do projeto (Morelagem).
Corrigir a escrita da palavra modelagem -> está "morelagem".

2022-02-17 22:35 UTC, IanFPFerreira requested changes
O pull request deveria ser feito para a branch documentation e não para a master

2022-02-18 01:40 UTC, IanFPFerreira approved these changes
Está tudo certo!

2022-02-18 02:03 UTC, guilhermemoraisr approved these changes
Tudo certo!

2022-02-18 02:03 UTC, merged