DiagramaDeClasses
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #81
Opened 2022-02-17 03:32 UTC by IanFPFerreira

## Issue 
Resolve #58

## Descrição
Criação do Diagrama de Classes

## Checklist:

- [ ] Não possui erros ortográficos
- [ ] O diagrama está coerente com a propsta da aplicação

2022-02-17 15:20 UTC, italovinicius18 requested changes

2022-02-17 15:20 UTC, italovinicius18 commented on docs/Modelagem/ME/DiagramaDeClasse.md
> +Desenvolvemos o Diagrama de Classes utilizando o site [Lucidchart](https://www.lucidchart.com/pages/), e para a sua criação, partimos do que definimos nos [requisitos elicitados](../../Base/PNOAE/Req
```suggestion
Desenvolvemos o Diagrama de Classes utilizando o site <a href="https://www.lucidchart.com/pages/" target="_blank">Lucidchart</a>, e para a sua criação, partimos do que definimos nos [requisitos elicitados](../../Base/PNOAE/Requisitos/Rastreabilidade/MatrizRastreabilidade.md), no [protótipo de alta fidelidade](../../Base/PNOAE/DesignSprint/Prototipacao/PrototipoAltaFidelidade.md) e principalmente, na [modelagem de dados](../IE/ModelagemDeDados.md)
```

2022-02-17 17:27 UTC, AlvaroLeles requested changes

2022-02-17 17:27 UTC, AlvaroLeles commented on docs/Modelagem/ME/DiagramaDeClasse.md
> +O Diagrama de Classes é um tipo de modelagem que tem como objetivo mostrar a estrutura de um sistema no nível de classes, ou seja, ele define quais as classes a aplicação terá, e define as suas carac
"... ele define quais as classes a aplicação terá...", ficou um pouco confuso, acredito que seria algo como "...quais as classes QUE a aplicação terá..."

2022-02-18 00:16 UTC, italovinicius18 approved these changes

2022-02-18 02:31 UTC, AlvaroLeles approved these changes

2022-02-18 02:31 UTC, merged