Guia estilo
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #93
Opened 2022-03-17 18:38 UTC by AlvaroLeles

## Issue 
Resolve #87 

## Descrição
Adição da página de Guia de Estilo

## Checklist:
- [ ] O código segue os padrões do projeto
- [ ] Ortografia correta
- [ ] Conteúdo apropriado

## Como validar?
Avaliar se o documento cumpre com os requisitos dados no tópico Checklist

2022-03-20 18:39 UTC, IanFPFerreira requested changes

2022-03-20 18:39 UTC, IanFPFerreira commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +Na aplicação haverá <i>dialogs</i> para comunicar ao usuário suas ações, sendo confirmações de ações como algo salvo com sucesso, requisições de confirmação, como algo se algo deve realmente ser excl
Na aplicação haverá <i>dialogs</i> para comunicar ao usuário suas ações, sendo confirmações de ações como algo salvo com sucesso, requisições de confirmação, como se algo deve realmente ser excluído, por exemplo, ou comunicações de erro.

2022-03-20 23:33 UTC, guilhermemoraisr requested changes
Alterar a palavra "palhetas" para "paleta" (forma correta) em seus 3 casos;
Faltou acento na palavra Introdução na tabela de versionamento.

2022-03-20 23:33 UTC, guilhermemoraisr commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +| 1.1 | 15/03/2022 | Introduçao do documento | Gabriel Avelino |
| 1.1 | 15/03/2022 | Introdução do documento | Gabriel Avelino |

2022-03-20 23:33 UTC, guilhermemoraisr commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +As palhetas de cores secundárias foram escolhidas para informações complementares como POP-UPS e alguns botões destacados.
As paleta de cores secundárias foram escolhidas para informações complementares como POP-UPS e alguns botões destacados.

2022-03-20 23:33 UTC, guilhermemoraisr commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +<center>Figura 10: Palhetas de cores secundárias</center>
<center>Figura 10: Paleta de cores secundárias</center>

2022-03-20 23:33 UTC, guilhermemoraisr commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +<center>Figura 9: Palhetas de cores principais</center>
<center>Figura 9: Paleta de cores principais</center>

2022-03-21 02:09 UTC, IanFPFerreira requested changes

2022-03-21 02:09 UTC, IanFPFerreira commented on docs/PadroesDeProjeto/IE/GuiaDeEstilo.md
> +| 1.4 | 17/03/2022 | Adição da seção Vocabulário e Padrões | Álvaro Leles |
Não encontrei nenhum erro no documento, basta colocar as revisões no versionamento e adicionar o meu nome e do Guilherme de Morais nesse novo versionamento

2022-03-21 02:15 UTC, IanFPFerreira approved these changes
Tudo certo!

2022-03-21 02:17 UTC, merged