GOFs
UnBArqDsw2021-2/2021.2_G3_stag.io pull request #97
Opened 2022-03-20 20:58 UTC by italovinicius18

## Issue 
Resolve #85 

## Descrição
Documentação dos GOFs

## Checklist:

- [ ] O código segue os padrões do projeto
- [ ] A gramática está correta

2022-03-20 22:43 UTC, gabrielavelino requested changes

2022-03-20 22:43 UTC, gabrielavelino commented on docs/PadroesDeProjeto/GOFs/GOFs.md
> +As interações entre objetos de um sistema pode causar grande dependência entre os elementos, de forma a aumentar a complexidade de eventuais alterações no funcionamento do sistema. Padrões estruturai
com como classes e objetos

2022-03-20 22:53 UTC, joaovaladao approved these changes
Apenas modificar as observações do Gabriel

2022-03-20 23:43 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/PadroesNaoUtilizados.md
> +Utiliza-se o Factory Method quando não souber de antemão os tipos e dependências exatas dos objetos com os quais seu código deve funcionar, ~ou seja, em razão do escopo menor do nosso projeto e que e
tem um "~" (, ~ou seja,)

2022-03-20 23:47 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/PadroesNaoUtilizados.md
> +Pensamos em implementar este padrão para facilitar na construção de estruturas que a aplicação e o banco de dados interpretasse, impedindo que possíveis tipagens fossem erroneas, porém o express já t
O correto seria "interpretassem"

2022-03-20 23:48 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/PadroesNaoUtilizados.md
> +Além do que não precisamos projetar comportamentos adicionais para objetos em tempo de execução, pois cada objeta já possui sua própria resposabilidade e é modularizado exatamente para ter esse objet
O correto seria "responsabilidade"

2022-03-20 23:49 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/PadroesNaoUtilizados.md
> +Pensamos em encapsular o fator de autenticação por meio de um decorator, especificando qual foi o valor inserido e assim resgatassémos o login daquele usuário e já identificassemos se é uma empresa o
O correto seria "resgatássemos" e "identificássemos"

2022-03-20 23:53 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/PadroesNaoUtilizados.md
> +Este padrão foi mencionado na hora estávamos debatendo, porém percebemos que seria algo que não precisariamos implementar, principlamente pelo fato de que o React já possui implementados funções que
O correto seria "precisaríamos", "principalmente" e "das variáveis"

2022-03-20 23:55 UTC, italofernandes13 commented on docs/PadroesDeProjeto/GOFs/GOFs.md
> +As interações entre objetos de um sistema pode causar grande dependência entre os elementos, de forma a aumentar a complexidade de eventuais alterações no funcionamento do sistema. Padrões estruturai
O correto seria "podem causar"

2022-03-20 23:56 UTC, italofernandes13 requested changes
Algumas imagens têm legendas e outras não.

2022-03-21 01:32 UTC, gabrielavelino approved these changes

2022-03-21 01:40 UTC, italofernandes13 approved these changes

2022-03-21 02:06 UTC, merged